In [ ]:

q = np.random.random([10,4])
q = q/np.linalg.norm(q)
print(q)

In [79]:
def gbc_angle(q1,Dl,Dr,s1,threshold):
 # still needs **kwargs to enable two misorientation angle choices like MTEX
 qs = Orientation(q1,s1)
 qs = qs.map_into_symmetry_reduced_zone
 
 print(qs)
 print(Dl)
 print(Dr)

 o1 = qs[Dl]
 o2 = qs[Dr]

 mis = o1*~o2 #angle(orientation(q(Dl),CS),orientation(q(Dr),CS))

 #print(d.angle) 
 # if np.ndarray.size(threshold) == 1:
 criterion = mis.angle < threshold

 return criterion
# else:
#  criterion = 0.5 * [[d.angle < threshold[1]] + [d.angle < threshold[2]]]
#  print(criterion)
# return criterion

from orix.quaternion import Orientation
from orix.quaternion import symmetry
import numpy as np

s1 = symmetry.get_point_group(226)

degree = np.pi/180

# orix wants radians, let's create some fake ones for now
q1 = Orientation(q,symmetry=s1)

Dl = np.zeros(10,dtype=bool)
Dl[0:5]=1
print(Dl)

Dr = np.zeros(10,dtype=bool)
Dr[5:10]=1
print(Dr)

# define as orix orientations and then hit that with o1*~o2

#print(o1)
#print(s1)
#print(5*degree)
criterion = gbc_angle(q1,Dl,Dr,s1,5*degree) 
print(criterion)




[ True  True  True  True  True False False False False False]
[False False False False False  True  True  True  True  True]
<bound method Misorientation.map_into_symmetry_reduced_zone of Orientation (10,) m-3m
[[0.6205 0.491  0.0261 0.611 ]
 [0.1706 0.514  0.7679 0.3422]
 [0.9171 0.3253 0.1682 0.1577]
 [0.2648 0.6835 0.5461 0.4054]
 [0.3538 0.0331 0.8923 0.2785]
 [0.2215 0.9067 0.1976 0.2998]
 [0.2207 0.4105 0.8006 0.3765]
 [0.251  0.6839 0.3212 0.605 ]
 [0.419  0.4011 0.2651 0.7702]
 [0.1411 0.6278 0.6547 0.3967]]>
[ True  True  True  True  True False False False False False]
[False False False False False  True  True  True  True  True]


TypeError: 'method' object is not subscriptable

In [9]:



def gbc_angle(o1,o2,CS,threshold):
 # still needs **kwargs to enable two misorientation angle choices like MTEX
 mis = o1*~o2 #angle(orientation(q(Dl),CS),orientation(q(Dr),CS))
 #print(d.angle)
 return mis
# if np.ndarray.size(threshold) == 1:
#  criterion = d.angle < threshold
# else:
#  criterion = 0.5 * [[d.angle < threshold[1]] + [d.angle < threshold[2]]]
#  print(criterion)
# return criterion

# define as orix orientations and then hit that with o1*~o2

#print(o1)
#print(s1)
#print(5*degree)
mis = gbc_angle(o1,o2,s1,5*degree) 
print(mis.angle)


[2.79788315]
[2.79788315]
